---

apiVersion: v1
kind: Service
metadata:
  name: {{ app_name }}
  namespace : {{ namespace }}
  labels:
    app: {{ app_name }}
    service: {{ app_name }}
spec:
  selector:
    app: {{ app_name }}
    service: {{ app_name }}
  ports:
    - protocol: TCP
      port: 3306
      target_port: 3306
