---
# TODO:
#  - centos vs rhel
#  - reference standard image streams?
service_name: "{{ lookup('env','SERVICE_NAME') | default('mysql', true) }}"
volume_size: "{{ lookup('env','VOLUME_SIZE') | default('10Gi', true) }}"
mysql_user: "{{ lookup('env','MYSQL_USER') | default('devel', true) }}"
mysql_database: "{{ lookup('env','MYSQL_DATABASE') | default('devel', true) }}"
mysql_version: "{{ lookup('env','MYSQL_VERSION') | default('5.7', true) }}"
image: "registry.access.redhat.com/rhscl/mysql-{{ mysql_version | replace('.', '')}}-rhel7"
state: present
